begin;

    drop table if exists message;

    create table message(
        id int primary key generated by default as identity ,
        data varchar
    );

    insert into message (data)
    select concat('Data ', number)
    from generate_series(1, 100) number;

end;